### ISSUE TITLE
Other configuration than @start for equinox bundles

### ISSUE THREAD

**Issue by JulianSchuette** [renatoathaydes/osgi-run#11]
Hello,

OsgiRuntimeTaskCreator.groovy:140 always creates equinox configs with all bundles set to "..:@start". This will result in ugly exceptions when trying to start fragment bundles, or even prevent configurations from running properly when bundles are required to be installed, but not started.

Is there any way to write configs with bundles not set to "..@start"?

Thank you!

**Comment by renatoathaydes** [comment]
Hi!

Sorry about that, I will try to fix as soon as possible.

For the moment, I think the only way to fix would be to add some groovy code to your build.gradle file that, after the osgiConfig task runs, changes the config file to remove the `@start` for the bundles you do not want started (ugly but may work for you).

**Comment by JulianSchuette** [comment]
Alright, thank you anyway.

**Comment by renatoathaydes** [comment]
you can leave this issue open until i fix it!

**Comment by it-productivity-user** [comment]
@JulianSchuette are you able to test my fix? This commit is in the 'next' branch.

**Comment by renatoathaydes** [comment]
This fix is now released in version 1.2.1, which you can download from JCenter.

I created a test project (see the commit) called bundle-with-fragment to make sure this works. Funnily enough, though, the previous version also worked fine even with the '@start' directive after the fragment bundle... I guess Equinox handles that gracefully... anyway, it's better now.

**Comment by JulianSchuette** [comment]
Tested and works. Thank you!
