### ISSUE TITLE
Object[]'s toString() used in wrapping

### ISSUE THREAD

**Issue by aborg0** [renatoathaydes/osgi-run#19]
In this [build.gradle](https://github.com/aborg0/rapidminer-studio/blob/7b77814bebad1c0931e446c4c627833c2013c16d/build.gradle) I am generating OSGi manifests for both the rsyntaxtextarea and its autocomplete. Unfortunately when I [tried to change](https://github.com/aborg0/rapidminer-studio/blob/7b77814bebad1c0931e446c4c627833c2013c16d/build.gradle#L80) the `org.fife.ui` symbolic name of RSyntaxTextArea, I got symbolic name like: `[Ljava.lang.Object;@69c8b868`.

When I tried similar thing to change the version of things to wrap, I got also a toString of an Object array (so I had to find already OSGified versions of it).

**Comment by renatoathaydes** [comment]
That's strange. I will fix as soon as possible. Thanks for reporting.

**Comment by renatoathaydes** [comment]
Closed by accident, sorry.
