### ISSUE TITLE
Improved version computation

### ISSUE THREAD

**Issue by aborg0** [renatoathaydes/osgi-run#20]
For the `com.thoughtworks.xstream:xstream:1.4.7` dependency there is an `xpp3:xpp3_min:1.1.4c` dependency, which cannot be wrapped, because the `1.1.4c` is not an OSGi version format and the bnd tool fails with an exception. (Similarly to the `org.apache.poi:poi-ooxml-schemas:3.10-FINAL` dependency, `3.10-FINAL` is not a valid OSGi version number, so bnd fails.) It would be nice if these kind of version numbers were automatically converted to an OSGi format, like `1.1.4.c` or `3.10.0.FINAL`.
Thanks for this great tool.

**Comment by renatoathaydes** [comment]
Oh, unfortunately I've just released version 1.3.1!!! If I'd seen this earlier I could've included a fix in this version... well, nothing I can't fix in a couple of weeks... normally, I try to add  at least "a few" new features in each version. Keep creating issues so I can fix them in 1.3.2 :)

**Comment by aborg0** [comment]
No worries, I have found alternatives, so there is a workaround in my case and with the fix for #19, every bundle can be fixed manually.
Thanks.

**Comment by renatoathaydes** [comment]
Please confirm this has been fixed with version 1.4.0 which I just released. It uses the newest bndlib version so I think this problem has gone away.
