### ISSUE TITLE
Generate source bundles for eclipse/equinox

### ISSUE THREAD

**Issue by aborg0** [renatoathaydes/osgi-run#21]
It would be nice when equinox is used in case there are no source bundles available (i.e. when wrapping or it was not uploaded to the repository) those bundles were generated. In Maven, this is done something like [this](http://rajakannappan.blogspot.hu/2010/03/automating-eclipse-source-bundle.html), while for gradle it is probably looks like `'-sources': true` in [this](https://github.com/TomDmitriev/gradle-bundle-plugin).
Thanks for considering it.

**Comment by renatoathaydes** [comment]
Hm... I am not familiar with source bundles. They seem to be an Equinox concept?

**Comment by aborg0** [comment]
I am not sure whether that is an equinox concept, but in eclipse in case that in not in the target platform, we have to add the source for each bundle manually, while if we add source bundles, those are automatically assigned (so this is probably more an eclipse concept). I think the main instruction for them is the following: `Eclipse-SourceBundle`, like `Eclipse-SourceBundle: com.mind_era.com.rapidminer.rapidminer-api;version="0.1.1";roots:="."` They usually have `.source` suffix in their symbolic name (and the same `Bundle-Version`), like `Bundle-SymbolicName: com.mind_era.com.rapidminer.rapidminer-api.source`. So this is just a convenience for development (and distribution).

**Comment by paulvi** [comment]
@aborg0 osgi-run now (since 1.4.3 #33) can be used together with https://github.com/TomDmitriev/gradle-bundle-plugin

**Comment by paulvi** [comment]
quote from https://github.com/ctron/package-drone/wiki/Cheatsheet

> This will not only import the bundle JAR and create a P2 repository, but also convert the Maven source attachment directly into an Eclipse Source bundle.

That is an idea to use external tools like repository manager to do the work

the project is now http://packagedrone.org/ at https://github.com/eclipse/packagedrone/
