### ISSUE TITLE
Remove dependency on the Gradle OSGi Plugin

### ISSUE THREAD

**Issue by renatoathaydes** [renatoathaydes/osgi-run#33]
Including the Gradle OSGi Plugin automatically was a decision that made sense when there was only one Gradle plugin for OSGi and to make it a tiny little bit easier for developers to use osgi-run (as they cannot forget to make their jars into bundles this way).

However, the Gradle OSGi Plugin only uses Bnd to create a manifest, not to modify the jar in any other way that is supported by Bnd, such as including nested jars (see #32 ), so this dependency on the Gradle OSGi Plugin is causing more damage than good for some users.

Removing this dependency should be really easy anyway.. Current users who don't explicitly declare `apply plugin: 'osgi'` just need to add this line to their build files and everything will work as before.

**Comment by paulvi** [comment]
There can be nicer path, that by default imply 
`apply plugin: 'osgi'`
but ask users to specify exactly.

Then if possible to support `gradle-bundle-plugin` or others

**Comment by renatoathaydes** [comment]
Fixed in version 1.4.3.
