### ISSUE TITLE
[examples] `allprojects {` in `build-with-subprojects` is applied to all `osgi-run-test` tree

### ISSUE THREAD

**Issue by paulvi** [renatoathaydes/osgi-run#34]
https://github.com/renatoathaydes/osgi-run/blob/master/osgi-run-test/build-with-subprojects/build.gradle#L13

`allprojects {` in `build-with-subprojects` is applied to all `osgi-run-test` tree,  
as set of project is defined by https://github.com/renatoathaydes/osgi-run/blob/master/osgi-run-test/settings.gradle

**Comment by renatoathaydes** [comment]
Hm.. not ideal, I did not realize it... but no much harm caused either... will remove that.

**Comment by paulvi** [comment]
it is all just quick example to test. But as a new user, I am looking to learn something from them.

**Comment by renatoathaydes** [comment]
@paulvi cool, hope you're learning something :) The intention of these samples is exactly to show people how to get things working with OSGi... and in my experience, `osgi-run` is the easiest way to develop with OSGi!

**Comment by renatoathaydes** [comment]
Fixed.
