### ISSUE TITLE
default console configuration for Equinox

### ISSUE THREAD

**Issue by paulvi** [renatoathaydes/osgi-run#38]
Just by chance ran into http://stackoverflow.com/questions/25733843/how-to-start-osgi-console, that gave me answer why possible I could not run one of my first examples against Equinox

The solution is pasted below. Can this be default e.g. for #37 run-any

> Make a run folder that would look like:

 - somedir/
     - configuration/
         - config.ini
     - org.eclipse.osgi.jar
     - org.eclipse.equinox.console.jar
     - org.apache.felix.gogo.shell.jar
     - org.apache.felix.gogo.command.jar
     - org.apache.felix.gogo.runtime.jar

> Then edit config.ini as:

osgi.bundles=org.apache.felix.gogo.runtime@start, org.apache.felix.gogo.command@start, org.apache.felix.gogo.shell@start, org.eclipse.equinox.console@start

> After done this, run `java -jar org.eclipse.osgi.jar -console` in your command line and the osgi console will start.

**Comment by renatoathaydes** [comment]
Equinox deprecated the `-console` option from version 3.8, so now we need to add a bunch more bundles to the default OSGi environment for the Equinox console to work?

Do I understand correctly? 

Notice that the `config.ini` is already built correctly to start all bundles, so that doesn't need any change.

**Comment by paulvi** [comment]
It reads so, I need to try

**Comment by paulvi** [comment]
asked http://stackoverflow.com/questions/36542524/run-latest-equinox-with-gradle-maven-tool

**Comment by renatoathaydes** [comment]
I've found a newer version of Equinox in Maven Central... you can use this to run with Java 8:

```groovy
osgiMain = 'org.eclipse:osgi:3.10.0-v20140606-1445'
```

But I could not find a console. Equinox artifacts in Maven Central are a mess...

**Comment by renatoathaydes** [comment]
If you really need it, you can download the jars from the [Equinox downloads page](http://download.eclipse.org/equinox/drops/R-Mars.2-201602121500/index.php) and use it as a flatJar dependency with Gradle (obviously, not portable)... but I don't see any public Maven repository that I can use to fetch the console jar with Gradle, unfortunately.

**Comment by renatoathaydes** [comment]
`osgi-run` version 1.5.2 will use Equinox artifact `org.osgi:org.eclipse.osgi:3.10.100.v20150529-1857` and run with the Gogo shell, which seems to be the current approach.
