### ISSUE TITLE
multiline javaArgs breaks run.sh script 

### ISSUE THREAD

**Issue by thugcee** [renatoathaydes/osgi-run#43]
example build.gradle fragment:
```
runOsgi {
    [...]
    javaArgs = '''
        -Djersey=true
        -Dosgi.clean=true 
    ''''
```

works for `./gradlew runOsgi` but `run.sh` script looks like this:

```
[...]
"$JAVA"
                -Djersey=true
                -Dosgi.clean=true 
         -jar org.apache.felix.main-5.4.0.jar  "$@"
```

There should be '\' at line ends.

**Comment by renatoathaydes** [comment]
Why don't you do this:

```
runOsgi {
    [...]
    javaArgs = '''\
        -Djersey=true\
        -Dosgi.clean=true \
    ''''
}
```

**Comment by thugcee** [comment]
I do :) but every time I edit and copy those properties between different launch environments, I have to run macro to add or strip the '\'.

**Comment by renatoathaydes** [comment]
Ok... well, I guess it never makes sense to have new-lines in javaArgs... so we can actually fix that.

**Comment by thugcee** [comment]
Thx .
and BTW great plugin :)
