### ISSUE TITLE
How to download sources of dependencies?

### ISSUE THREAD

**Issue by svatos-jirka** [renatoathaydes/osgi-run#65]
Hello,

how to download sources of dependencies (even transitive?)

with best regards, jiri

**Comment by renatoathaydes** [comment]
Hi, this is most likely a Gradle question.
I think you might be able to do it by specifying a qualifier in the dependency declaration.

See https://stackoverflow.com/questions/28404149/how-to-download-javadocs-and-sources-for-jar-using-gradle-2-0

Example:

```groovy
compile "commons-codec:commons-codec:1.10:sources"
```

**Comment by svatos-jirka** [comment]
?? what does it mean? Must I specify for each dependency new line with dependency which ends:sources?

No, it could be true??
