### ISSUE TITLE
Doesnt work under gradle 4.4.1

### ISSUE THREAD

**Issue by svatos-jirka** [renatoathaydes/osgi-run#68]
Hi,

It seems, that it doesnt work under gradle 4.4.1. We migrated from gradle 3.4. Main issue is, that generated configuration.ini and content of folder plugins is different.

The main difference,  **that start level is changed (I really dont know why)** and osgiaas-cli-core is added:

__osgiRuntime__0
\--- org.apache.felix:org.apache.felix.scr:2.0.12

__osgiRuntime__1
\--- com.athaydes.osgiaas:osgiaas-cli-core:0.7
     +--- com.athaydes.osgiaas:osgiaas-cli-api:0.7
     |    +--- com.athaydes.osgiaas:osgiaas-common:0.7
     |    \--- org.apache.felix:org.apache.felix.shell:1.4.3
     \--- jline:jline:2.14.2

It looks like, that dependencies are handled by different way. Why? 

It looks like, that level for start level is copied to transitive deps

Please help, with best regards, jiri

**Comment by renatoathaydes** [comment]
`osgiaas-cli-core` is the new CLI that replaces Felix Gogo. You can replace it by explicitly listing all bundles that should be deployed, something like this:

```groovy
runOsgi {
    bundles += allprojects.toList() + FELIX_GOGO_BUNDLES
}
```

This will revert to the old Gogo shell.

Regarding Gradle upgrade issues, can you please post the error message you get?

Start levels are only changed if you specify that in a dependency like this:

```groovy
dependencies {
    compile osgi("org:artifact:version:startLevel")
}
```

**Comment by svatos-jirka** [comment]
Hi, 

firstly: Thanks, I overlooked CLI feature.

**Comment by renatoathaydes** [comment]
Version 2.0 of this plugin now works on Gradle 7.4+.
