### ISSUE TITLE
ipojo-plugin: Upload version 1.1 to Bintray

### ISSUE THREAD

**Issue by meowy** [renatoathaydes/osgi-run#8]
The current version of ipojo-plugin is 1.0 on Bintray and therefore doesn't include commit 0b2b7bb2, which fixes a bug that prevents rebuilding without removing the existing generated bundle. ipojo-plugin 1.1 should be made available to fix this issue.

**Comment by renatoathaydes** [comment]
Oh, sorry about that. I will make a 1.1 release ASAP. Please let me know if you find any other issues that I can include in 1.1! Thanks.

**Comment by renatoathaydes** [comment]
Pushed ipojo-plugin 1.1 to JCenter! Please let me know if you still have any problems.

**Comment by meowy** [comment]
Thanks!
