### ISSUE TITLE
Relative bundle paths (Equinox)

### ISSUE THREAD

**Issue by JulianSchuette** [renatoathaydes/osgi-run#9]
Hello,

I am using `createOsgiRuntime` to generate an Equinox config, which works perfectly well. However, in the generated config.ini, bundles are given by absolute paths which makes it impossible to run the generated config from anywhere else then from target dir.

Bundles should be referred to by paths relative to the OSGi root. Does anything speak against replacing 
```
        def bundleJars = new FileNameByRegexFinder().getFileNames(
                bundlesDir.absolutePath, /.+\.jar/ )
```
by 
```
        def bundleJars = new FileNameByRegexFinder().getFileNames(
                new File(${osgiConfig.bundlesPath}").path, /.+\.jar/ )
```

in OsgiRuntimeTaskCreator.groovy:138 ?

**Comment by renatoathaydes** [comment]
Hi Julian,

Thank you for letting me know about this! I guess your suggestion is very good, if you want just make a pull request with this change and I can merge and release a new version of the plugin!

As long as this change does not break the tests and works for all use-cases it used to, of course, which I think seems to be the case.

Cheers.

**Comment by renatoathaydes** [comment]
Version 1.2 of osgi-run-core has just been released. I've added a few more improvements as well. Check the release notes: https://github.com/renatoathaydes/osgi-run/blob/master/osgi-run-core/release-notes.txt
